version: '3.7'

volumes:
    postgres-db:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /efs/volumes/postgresql/db
    
    mongo-db: 
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /efs/volumes/mongo/db

services:
  postgresql:
    image: postgres:latest
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST_AUTH_METHOD: md5
        TZ: America/Bogota
    ports:
        - 5432:5432
    restart: always
    volumes:
        - postgres-db:/var/lib/postgresql/data
        - ./postgresql/init:/docker-entrypoint-initdb.d/

  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-db:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@localhost:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
        - mongodb

  